/*-----------------------------------
Name: Sushant Moon
Roll number: CS1807
Date: 28 August, 2018
Program description: We know that the first two Fibonacci numbers are 0 and 1, and the successive Fibonacci
numbers are generated by adding the preceding two numbers in the sequence. Now consider
another sequence where we are given the first k numbers, and every number after that is
generated by multiplying the previous k numbers in the sequence. If k = 3, and we are given
1, 2, 3 as the first three numbers, then the 4th, 5th and 6th numbers in the sequence are 6,
36 and 648, respectively. Given n, k, and the first k numbers, your objective is to print the
nth number from that sequence. You should try to minimize the number of multiplications
needed. 

Run using : gcc -g -Wall cs1807-assign1-prog1.c -o prog1 -lm


Acknowledgements:
------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#define MALLOC(type, n) (type *)malloc(sizeof(type)*n)

int main()
{
    int n,k;
    scanf("%d %d", &n, &k);
    int *a = MALLOC(int, n);
    int i,m=0;
    int result = 1;
    for(i = 0; i < k; i++){
        scanf("%d", &a[i]);
        result *= a[i];
        m++;
    }

    i = 0;
    while(k < n){
        a[k] = result;
        result = ((result * result) / a[i]);
        m++;
        k++;
        i++;
    }
    // printf("%dth number in sequence is = %d\nTotal Multiplications required is = %d\n", k, a[k-1], m);
    printf("%d\n", a[k-1]);
    return 0;
}
